# Setup
title:               南荣相如
tagline:             '少即是多'
description:         '少即是多'
url:                 https://home.nanrong.store
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              南荣相如
  url:               https://home.nanrong.store
  email:             1282301776@qq.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
