# Setup
title:               南荣相如
tagline:             '少即是多'
description:         '在这个充满无限可能的数字时代，我们带您探索这些领域的无穷魅力和令人着迷的奥秘。'
url:                 https://zcqiand.github.io/nanrong
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              南荣相如
  url:               https://zcqiand.github.io/nanrong
  email:             1282301776@qq.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
