# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: 南荣相如
tagline: "南荣相如"
description: "欢迎来到南荣相如的主页，在这个充满无限可能的数字时代，南荣相如带您探索这些领域的无穷魅力和令人着迷的奥秘。"
url: https://zcqiand.github.io/nanrong
baseurl: /

author:
  name: "南荣相如"
  url: https://twitter.com/mdo

paginate: 5

# Custom vars
version: 1.0.0

github:
  repo: https://github.com/zcqiand
