name: sync-gitee

on:
  push:
    branches: ["main"]
    
jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/zcqiand
        dst: gitee/zcqiand
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "nanrong"
        force_update: true
